/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quepa_quepasa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static quepa_quepasa.cliente.r;

/**
 *
 * @author javisama
 */
public class articulos extends javax.swing.JFrame {

    /**
     * Creates new form articulos
     */
    public articulos() throws SQLException {
        initComponents();
        String url = "jdbc:mysql://localhost:3306/base_01";
        String user = "root";
        String pass = "";
        Connection connection = DriverManager.getConnection(url, user, pass);

        Statement s = connection.createStatement();
        String query = "select * from articulos";
        r = s.executeQuery(query);
        r.first();
        bcodigoarticulo.setText(r.getString("COD_ARTICULO"));
        barticulo.setText(r.getString("ARTICULO"));
        bfabricante.setText(r.getString("FABRICANTE"));
        bpeso.setText(r.getString("PESO"));
        bcategoria.setText(r.getString("CATEGORIA"));
        bprecio_venta.setText(r.getString("PRECIO_VENTA"));
        bprecio_coste.setText(r.getString("PRECIO_COSTE"));
        bexistencias.setText(r.getString("EXISTENCIAS"));
        CONFIRMAR.setVisible(false);
        CANCELAR.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigo_articulo = new javax.swing.JLabel();
        articulo = new javax.swing.JLabel();
        fabricante = new javax.swing.JLabel();
        peso = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        precio_venta = new javax.swing.JLabel();
        precio_coste = new javax.swing.JLabel();
        existencias = new javax.swing.JLabel();
        bcodigoarticulo = new javax.swing.JTextField();
        barticulo = new javax.swing.JTextField();
        bfabricante = new javax.swing.JTextField();
        bpeso = new javax.swing.JTextField();
        bcategoria = new javax.swing.JTextField();
        bprecio_venta = new javax.swing.JTextField();
        bprecio_coste = new javax.swing.JTextField();
        bexistencias = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        CONFIRMAR = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ARTICULOS");

        codigo_articulo.setText("CODIGO_ARTICULO");

        articulo.setText("ARTICULO");

        fabricante.setText("FABRICANTE");

        peso.setText("PESO");

        categoria.setText("CATEGORIA");

        precio_venta.setText("PRECIO VENTA");

        precio_coste.setText("PRECIO_COSTE");

        existencias.setText("EXISTENCIAS");

        jButton1.setText("ANTERIOR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("PRIMERA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SIGUIENTE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ULTIMA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("NUEVA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("EDITAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        CONFIRMAR.setText("CONFIRMAR");
        CONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIRMARActionPerformed(evt);
            }
        });

        CANCELAR.setText("CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(articulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigo_articulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(fabricante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(peso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precio_venta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precio_coste, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(existencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bcodigoarticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(barticulo)
                            .addComponent(bfabricante)
                            .addComponent(bpeso)
                            .addComponent(bcategoria)
                            .addComponent(bprecio_venta)
                            .addComponent(bprecio_coste)
                            .addComponent(bexistencias))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CONFIRMAR)
                        .addGap(18, 18, 18)
                        .addComponent(CANCELAR)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigo_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bcodigoarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(articulo)
                            .addComponent(barticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bfabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(peso)
                                    .addComponent(bpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(precio_venta)
                                    .addComponent(bprecio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precio_coste))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bprecio_coste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CONFIRMAR)
                            .addComponent(CANCELAR))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existencias)
                    .addComponent(bexistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            r.first();
            bcodigoarticulo.setText(r.getString("COD_ARTICULO"));
            barticulo.setText(r.getString("ARTICULO"));
            bfabricante.setText(r.getString("FABRICANTE"));
            bpeso.setText(r.getString("PESO"));
            bcategoria.setText(r.getString("CATEGORIA"));
            bprecio_venta.setText(r.getString("PRECIO_VENTA"));
            bprecio_coste.setText(r.getString("PRECIO_COSTE"));
            bexistencias.setText(r.getString("EXISTENCIAS"));   // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            r.previous();
            bcodigoarticulo.setText(r.getString("COD_ARTICULO"));
            barticulo.setText(r.getString("ARTICULO"));
            bfabricante.setText(r.getString("FABRICANTE"));
            bpeso.setText(r.getString("PESO"));
            bcategoria.setText(r.getString("CATEGORIA"));
            bprecio_venta.setText(r.getString("PRECIO_VENTA"));
            bprecio_coste.setText(r.getString("PRECIO_COSTE"));
            bexistencias.setText(r.getString("EXISTENCIAS"));   // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            r.next();
            bcodigoarticulo.setText(r.getString("COD_ARTICULO"));
            barticulo.setText(r.getString("ARTICULO"));
            bfabricante.setText(r.getString("FABRICANTE"));
            bpeso.setText(r.getString("PESO"));
            bcategoria.setText(r.getString("CATEGORIA"));
            bprecio_venta.setText(r.getString("PRECIO_VENTA"));
            bprecio_coste.setText(r.getString("PRECIO_COSTE"));
            bexistencias.setText(r.getString("EXISTENCIAS"));   // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            r.last();
            bcodigoarticulo.setText(r.getString("COD_ARTICULO"));
            barticulo.setText(r.getString("ARTICULO"));
            bfabricante.setText(r.getString("FABRICANTE"));
            bpeso.setText(r.getString("PESO"));
            bcategoria.setText(r.getString("CATEGORIA"));
            bprecio_venta.setText(r.getString("PRECIO_VENTA"));
            bprecio_coste.setText(r.getString("PRECIO_COSTE"));
            bexistencias.setText(r.getString("EXISTENCIAS"));   // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        bcodigoarticulo.setEditable(true);
        bcodigoarticulo.setText(" ");
        barticulo.setText(" ");
        bfabricante.setText(" ");
        bpeso.setText(" ");
        bcategoria.setText(" ");
        bprecio_venta.setText(" ");
        bprecio_coste.setText(" ");
        bexistencias.setText(" ");

        CONFIRMAR.setVisible(true);
        CANCELAR.setVisible(true);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton6.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        try {
            r.first();
            bcodigoarticulo.setEditable(true);
            bcodigoarticulo.setText(r.getString("COD_ARTICULO"));
            barticulo.setText(r.getString("ARTICULO"));
            bfabricante.setText(r.getString("FABRICANTE"));
            bpeso.setText(r.getString("PESO"));
            bcategoria.setText(r.getString("CATEGORIA"));
            bprecio_venta.setText(r.getString("PRECIO_VENTA"));
            bprecio_coste.setText(r.getString("PRECIO_COSTE"));
            bexistencias.setText(r.getString("EXISTENCIAS"));
            CANCELAR.setVisible(false);
            CONFIRMAR.setVisible(false);
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton6.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELARActionPerformed

    private void CONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRMARActionPerformed
        try {
            String vbcodigoarticulo, vbarticulo, vbfabricante, vbpeso, vbcategoria, vbprecio_venta, vprecio_coste, vbexistencias;
            vbcodigoarticulo = bcodigoarticulo.getText();
            vbfabricante = bfabricante.getText();
            vbpeso = bpeso.getText();
            vbcategoria = bcategoria.getText();
            vbprecio_venta = bprecio_venta.getText();
            vprecio_coste = precio_coste.getText();
            vbexistencias = bexistencias.getText();
            String url = "jdbc:mysql://localhost:3306/base_01";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement();
            String query = "insert into cliente values('" + vbcodigoarticulo + "','" + vbfabricante + "','" + vbpeso + "','" + vbcategoria + "','" + vbprecio_venta + "','" + vprecio_coste + "','" + vbexistencias + "')";
            int resultado = s.executeUpdate(query);
            r.refreshRow();

            CONFIRMAR.setVisible(false);
            CANCELAR.setVisible(false);
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton6.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CONFIRMARActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {

            String vbcodigoarticulo, vbarticulo, vbfabricante, vbpeso, vbcategoria, vbprecio_venta, vprecio_coste, vbexistencias;
            vbcodigoarticulo = bcodigoarticulo.getText();
            vbarticulo = barticulo.getText();
            vbfabricante = bfabricante.getText();
            vbpeso = bpeso.getText();
            vbcategoria = bcategoria.getText();
            vbprecio_venta = bprecio_venta.getText();
            vprecio_coste = precio_coste.getText();
            vbexistencias = bexistencias.getText();

            String url = "jdbc:mysql://localhost:3306/base_01";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement();
            String query = "update articulos set EXISTENCIAS='" + vbexistencias + "', ARTICULO='" + vbarticulo + "', FABRICANTE='" + vbfabricante + "', PESO ='" + vbpeso + "'  , CATEGORIA='" + vbcategoria + "'  , PRECIO_VENTA='" + vbprecio_venta + "', PRECIO_COSTE ='" + vprecio_coste + "' WHERE COD_ARTICULO ='" + vbcodigoarticulo + "'";
            int resultado = s.executeUpdate(query);
            r.refreshRow();
        } catch (SQLException ex) {
            Logger.getLogger(articulos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new articulos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(articulos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton CONFIRMAR;
    private javax.swing.JLabel articulo;
    private javax.swing.JTextField barticulo;
    private javax.swing.JTextField bcategoria;
    private javax.swing.JTextField bcodigoarticulo;
    private javax.swing.JTextField bexistencias;
    private javax.swing.JTextField bfabricante;
    private javax.swing.JTextField bpeso;
    private javax.swing.JTextField bprecio_coste;
    private javax.swing.JTextField bprecio_venta;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel codigo_articulo;
    private javax.swing.JLabel existencias;
    private javax.swing.JLabel fabricante;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel peso;
    private javax.swing.JLabel precio_coste;
    private javax.swing.JLabel precio_venta;
    // End of variables declaration//GEN-END:variables
}
